spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
  cassandra:
    keyspace-name: tacocloud
    schema-action: recreate
    local-datacenter: datacenter1
    contact-points:
      - casshost-1.tacocloud.com
      - casshost-2.tacocloud.com
      - casshost-3.tacocloud.com
    username: tacocloud
    password: 64ubamed
  data:
    mongodb:
      host: localhost
      port: 27017
      database: tacocloud