spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
  cassandra:
    keyspace-name: tacocloud
    local-datacenter: datacenter1
    contact-points:
      - casshost-1.tacocloud.com
      - casshost-2.tacocloud.com
      - casshost-3.tacocloud.com
    port: 9043
    username: tacocloud
    password: 64ubamed
  mongodb:
    host: mongodb.tacocloud.com
    port: 27017
    username: tacocloud
    password: 64ubamed
    database: tacoclouddb